# Generated by Django 5.0.7 on 2026-06-05 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0012_currency_and_company_locale'),
        ('cdr3cx', '0014_callrecord_vendor_neutral'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_pbx', models.CharField(default='3cx', max_length=20)),
                ('external_id', models.CharField(max_length=128)),
                ('display_name', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acd_agents', to='accounts.company')),
                ('extension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acd_agent_profile', to='accounts.extension')),
            ],
            options={
                'ordering': ['company', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='Disposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('label', models.CharField(max_length=64)),
                ('is_resolution', models.BooleanField(default=False, help_text='Counts toward operational FCR approximation')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositions', to='accounts.company')),
            ],
            options={
                'ordering': ['company', 'code'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_pbx', models.CharField(default='3cx', max_length=20)),
                ('external_id', models.CharField(help_text='Vendor queue id/DN (3CX queue extension, CUCM hunt pilot, etc.)', max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('sla_target_seconds', models.PositiveIntegerField(default=20)),
                ('sla_target_pct', models.PositiveIntegerField(default=80)),
                ('short_abandon_seconds', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acd_queues', to='accounts.company')),
            ],
            options={
                'ordering': ['company', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CallLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('leg_type', models.CharField(choices=[('inbound', 'Inbound'), ('queue', 'Queue'), ('agent', 'Agent'), ('transfer', 'Transfer')], max_length=20)),
                ('ring_sec', models.IntegerField(blank=True, null=True)),
                ('wait_sec', models.IntegerField(blank=True, null=True)),
                ('talk_sec', models.IntegerField(blank=True, null=True)),
                ('hold_sec', models.IntegerField(blank=True, null=True)),
                ('wrap_sec', models.IntegerField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acd.agent')),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='cdr3cx.callrecord')),
                ('disposition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acd.disposition')),
                ('queue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acd.queue')),
            ],
            options={
                'ordering': ['call', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_pbx', models.CharField(default='3cx', max_length=20)),
                ('external_id', models.CharField(blank=True, default='', max_length=128)),
                ('storage_url', models.CharField(blank=True, default='', max_length=512)),
                ('duration_sec', models.IntegerField(blank=True, null=True)),
                ('transcript', models.TextField(blank=True, default='')),
                ('sentiment', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='cdr3cx.callrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acd_teams', to='accounts.company')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company', 'name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.AddField(
            model_name='queue',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queues', to='acd.team'),
        ),
        migrations.AddField(
            model_name='agent',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='acd.team'),
        ),
        migrations.CreateModel(
            name='ThresholdPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sla_target_seconds', models.PositiveIntegerField(default=20)),
                ('sla_target_pct', models.PositiveIntegerField(default=80)),
                ('short_abandon_seconds', models.PositiveIntegerField(default=10)),
                ('amber_wait_seconds', models.PositiveIntegerField(default=90)),
                ('red_wait_seconds', models.PositiveIntegerField(default=120)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threshold_policies', to='accounts.company')),
                ('queue', models.ForeignKey(blank=True, help_text='Null = company-wide default', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threshold_policies', to='acd.queue')),
            ],
            options={
                'ordering': ['company', 'queue'],
            },
        ),
        migrations.CreateModel(
            name='AgentStateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('on_call', 'On Call'), ('wrap', 'Wrap'), ('not_ready', 'Not Ready'), ('offline', 'Offline')], db_index=True, max_length=16)),
                ('reason_code', models.CharField(blank=True, default='', max_length=32)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_events', to='acd.agent')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['agent', '-started_at'], name='acd_agentst_agent_i_b64945_idx')],
            },
        ),
        migrations.CreateModel(
            name='QueueMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_memberships', to='acd.agent')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='acd.queue')),
            ],
            options={
                'unique_together': {('queue', 'agent')},
            },
        ),
        migrations.AddIndex(
            model_name='queue',
            index=models.Index(fields=['company', 'is_active'], name='acd_queue_company_fb8da4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='queue',
            unique_together={('company', 'source_pbx', 'external_id')},
        ),
        migrations.AlterUniqueTogether(
            name='agent',
            unique_together={('company', 'source_pbx', 'external_id')},
        ),
        migrations.AlterUniqueTogether(
            name='thresholdpolicy',
            unique_together={('company', 'queue')},
        ),
    ]
