# Generated by Django 5.0.7 on 2026-06-05 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='is_acd_queue',
            field=models.BooleanField(db_index=True, default=False, help_text='True = a real 3CX ACD queue (XAPI-sourced, has agent-wait timing). False = an IVR/DN-derived pseudo-queue from the socket CDR.'),
        ),
        migrations.CreateModel(
            name='QueueDailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_date', models.DateField(db_index=True)),
                ('calls', models.IntegerField(default=0)),
                ('answered', models.IntegerField(default=0)),
                ('ring_time_seconds', models.FloatField(blank=True, help_text='Total ring/wait seconds', null=True)),
                ('talk_time_seconds', models.FloatField(blank=True, help_text='Total talk seconds', null=True)),
                ('avg_ring_seconds', models.FloatField(blank=True, help_text='ASA as reported by 3CX', null=True)),
                ('avg_talk_seconds', models.FloatField(blank=True, null=True)),
                ('callbacks', models.IntegerField(default=0)),
                ('source', models.CharField(default='3cx_xapi', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='acd.queue')),
            ],
            options={
                'ordering': ['-stat_date'],
                'indexes': [models.Index(fields=['queue', 'stat_date'], name='acd_queueda_queue_i_b4dc1a_idx')],
                'unique_together': {('queue', 'stat_date')},
            },
        ),
    ]
