# Generated by Django 5.0.7 on 2026-06-06 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acd', '0002_queue_is_acd_queue_queuedailystats'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentQueueDailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_dn', models.CharField(db_index=True, max_length=32)),
                ('agent_name', models.CharField(blank=True, default='', max_length=128)),
                ('stat_date', models.DateField(db_index=True)),
                ('answered', models.IntegerField(default=0)),
                ('lost', models.IntegerField(default=0, help_text='Rings to this agent that went unanswered')),
                ('answered_pct', models.IntegerField(default=0)),
                ('logged_in_seconds', models.FloatField(blank=True, null=True)),
                ('ring_time_seconds', models.FloatField(blank=True, null=True)),
                ('avg_ring_seconds', models.FloatField(blank=True, null=True)),
                ('talk_time_seconds', models.FloatField(blank=True, null=True)),
                ('avg_talk_seconds', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(default='3cx_xapi', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_daily_stats', to='acd.queue')),
            ],
            options={
                'ordering': ['-stat_date', 'agent_dn'],
                'indexes': [models.Index(fields=['queue', 'stat_date'], name='acd_agentqu_queue_i_78f298_idx')],
                'unique_together': {('queue', 'agent_dn', 'stat_date')},
            },
        ),
        migrations.CreateModel(
            name='QueueAbandonedCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='3CX CallHistoryId (stable per call)', max_length=128)),
                ('call_time', models.DateTimeField(db_index=True)),
                ('wait_seconds', models.FloatField(blank=True, help_text='Seconds the caller waited before abandoning', null=True)),
                ('caller_id', models.CharField(blank=True, default='', max_length=64)),
                ('last_agent_dn', models.CharField(blank=True, default='', max_length=32)),
                ('last_agent_name', models.CharField(blank=True, default='', max_length=128)),
                ('polling_attempts', models.IntegerField(default=0, help_text='Number of agents the call rang before it was abandoned')),
                ('was_logged_in', models.BooleanField(default=False, help_text='At least one agent was logged in when abandoned')),
                ('source', models.CharField(default='3cx_xapi', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abandoned_calls', to='acd.queue')),
            ],
            options={
                'ordering': ['-call_time'],
                'indexes': [models.Index(fields=['queue', 'call_time'], name='acd_queueab_queue_i_3089ed_idx')],
                'unique_together': {('queue', 'external_id')},
            },
        ),
    ]
