# Generated by Django 5.0.7 on 2026-06-06 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acd', '0003_agentqueuedailystats_queueabandonedcall'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_date', models.DateField(db_index=True)),
                ('metric', models.CharField(choices=[('answer_rate', 'Answer rate below target'), ('asa', 'ASA above threshold'), ('abandon_wait', 'Abandon wait above threshold')], max_length=20)),
                ('severity', models.CharField(choices=[('amber', 'Amber'), ('red', 'Red')], db_index=True, max_length=8)),
                ('value', models.FloatField(help_text='Observed value that breached (seconds or %)')),
                ('threshold', models.FloatField(help_text='Threshold it breached')),
                ('message', models.CharField(blank=True, default='', max_length=255)),
                ('notified', models.BooleanField(default=False, help_text='Email dispatch attempted')),
                ('recipient', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='acd.queue')),
            ],
            options={
                'ordering': ['-stat_date', 'queue', 'metric'],
                'indexes': [models.Index(fields=['queue', 'stat_date'], name='acd_queueal_queue_i_6892a4_idx')],
                'unique_together': {('queue', 'stat_date', 'metric', 'severity')},
            },
        ),
    ]
