# Generated by Django 5.0.7 on 2026-06-06 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_company_pbx_api_password_company_pbx_api_url_and_more'),
        ('acd', '0004_queuealert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('report_type', models.CharField(choices=[('callcenter_summary', 'Call Center Summary'), ('queue_performance', 'Queue Performance (real ACD)'), ('agent_productivity', 'Agent Productivity'), ('sla_breaches', 'SLA Breach Alerts')], max_length=32)),
                ('window', models.CharField(choices=[('yesterday', 'Yesterday'), ('last_7_days', 'Last 7 days'), ('last_30_days', 'Last 30 days'), ('week_to_date', 'Week to date'), ('month_to_date', 'Month to date'), ('last_month', 'Last month')], default='yesterday', max_length=20)),
                ('fmt', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel'), ('pdf', 'PDF'), ('html', 'HTML')], default='xlsx', max_length=8, verbose_name='Format')),
                ('recurrence', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10)),
                ('hour', models.PositiveSmallIntegerField(default=8, help_text='Hour of day (0-23), tenant timezone')),
                ('minute', models.PositiveSmallIntegerField(default=0)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0, help_text='For weekly recurrence')),
                ('day_of_month', models.PositiveSmallIntegerField(default=1, help_text='For monthly recurrence (1-28)')),
                ('recipients', models.TextField(help_text='Email addresses, comma or newline separated')),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=32)),
                ('window', models.CharField(max_length=20)),
                ('fmt', models.CharField(max_length=8)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=8)),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('file_path', models.CharField(blank=True, default='', max_length=512)),
                ('row_count', models.IntegerField(default=0)),
                ('recipients', models.CharField(blank=True, default='', max_length=512)),
                ('emailed', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_runs', to='accounts.company')),
                ('scheduled_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='acd.scheduledreport')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', '-created_at'], name='acd_reportr_company_d3e1df_idx')],
            },
        ),
    ]
