# Generated by Django 5.0.7 on 2026-06-06 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_company_pbx_api_password_company_pbx_api_url_and_more'),
        ('acd', '0005_scheduledreport_reportrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallDailyRollup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('cc_total', models.IntegerField(default=0, help_text='Call-center calls offered')),
                ('cc_answered', models.IntegerField(default=0)),
                ('cc_missed', models.IntegerField(default=0)),
                ('total_talk_seconds', models.BigIntegerField(default=0)),
                ('source', models.CharField(default='callrecord', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_rollups', to='accounts.company')),
            ],
            options={
                'ordering': ['-day'],
                'indexes': [models.Index(fields=['company', 'day'], name='acd_calldai_company_34dfcc_idx')],
                'unique_together': {('company', 'day')},
            },
        ),
    ]
