# Generated by Django 5.1.4 on 2026-05-12 01:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0012_currency_and_company_locale'),
        ('cdr3cx', '0014_callrecord_vendor_neutral'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('rule_type', models.CharField(choices=[('intl_spike', 'International call spike'), ('after_hours_intl', 'After-hours international'), ('premium_destination', 'Premium-rate destination'), ('blacklist_country', 'Blacklisted country'), ('velocity_calls', 'Velocity — calls per minute'), ('velocity_cost', 'Velocity — cost per hour'), ('velocity_duration', 'Velocity — duration per day'), ('new_destination', 'First call to a country'), ('long_intl', 'Long international call'), ('concurrent_calls', 'Concurrent calls per extension')], max_length=32)),
                ('threshold', models.DecimalField(decimal_places=2, help_text='Numeric threshold meaning depends on rule_type', max_digits=12)),
                ('time_window_minutes', models.PositiveIntegerField(default=60, help_text='Evaluation window in minutes')),
                ('countries', models.JSONField(blank=True, default=list, help_text='ISO country codes (for blacklist / premium rules)')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('action', models.CharField(choices=[('alert', 'Alert only'), ('disable_extension', 'Auto-disable extension'), ('block_route', 'Block route at SBC')], default='alert', max_length=32)),
                ('notify_emails', models.JSONField(blank=True, default=list)),
                ('notify_sms', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('shadow_mode', models.BooleanField(default=True, help_text='Log incidents but do not execute action (recommended for first 2 weeks)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_rules', to='accounts.company')),
            ],
            options={
                'ordering': ['company', 'severity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FraudIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('summary', models.CharField(max_length=255)),
                ('detail', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('false_positive', 'False positive')], db_index=True, default='open', max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notification_dispatched', models.BooleanField(default=False)),
                ('action_executed', models.CharField(blank=True, default='', max_length=32)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_incidents', to='accounts.company')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_fraud_incidents', to=settings.AUTH_USER_MODEL)),
                ('triggering_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cdr3cx.callrecord')),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='billing.fraudrule')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'KSA VAT 15%', 'UAE VAT 5%'", max_length=64)),
                ('country_code', models.CharField(db_index=True, help_text='ISO 3166-1 alpha-2 (SA, AE, EG…)', max_length=2)),
                ('rate_percent', models.DecimalField(decimal_places=2, help_text='e.g. 15.00 for 15%', max_digits=5)),
                ('applies_to', models.CharField(choices=[('SUBSCRIPTION', 'Subscription only'), ('USAGE', 'Usage only'), ('BOTH', 'Subscription + Usage')], default='BOTH', max_length=20)),
                ('effective_from', models.DateField(default=django.utils.timezone.now)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, help_text='If set, overrides country default for this tenant only', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_rules', to='accounts.company')),
            ],
            options={
                'ordering': ['country_code', '-effective_from'],
            },
        ),
        migrations.AddIndex(
            model_name='fraudrule',
            index=models.Index(fields=['company', 'is_active', 'rule_type'], name='billing_fra_company_196765_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudincident',
            index=models.Index(fields=['company', 'status', '-detected_at'], name='billing_fra_company_28fb1a_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudincident',
            index=models.Index(fields=['severity', 'status'], name='billing_fra_severit_74906a_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrule',
            index=models.Index(fields=['country_code', 'is_active'], name='billing_tax_country_eff3cd_idx'),
        ),
    ]
