# Generated by Django 5.0.7 on 2024-08-07 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_alter_extension_options_alter_extension_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota_limit', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
                ('balance_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=True)),
                ('is_excluded', models.BooleanField(default=False)),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.extension')),
            ],
            options={
                'ordering': ['-start_date', 'extension__extension'],
                'unique_together': {('extension', 'start_date', 'balance_frequency')},
            },
        ),
    ]
