# Generated by Django 5.0.7 on 2025-07-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdr3cx', '0011_quota_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='callpattern',
            name='name',
            field=models.CharField(default='', help_text='Name of the calling rule', max_length=100),
        ),
    ]
