# Generated by Django 5.0.3 on 2025-07-06 22:16

from django.db import migrations

def populate_callpattern_names(apps, schema_editor):
    CallPattern = apps.get_model('cdr3cx', 'CallPattern')
    for pattern in CallPattern.objects.all():
        if not pattern.name:
            # Generate a meaningful name based on pattern and type
            call_type_display = pattern.call_type.title() if pattern.call_type else "Unknown"
            pattern.name = f"{call_type_display} - {pattern.pattern}"
            pattern.save()

def reverse_populate_callpattern_names(apps, schema_editor):
    CallPattern = apps.get_model('cdr3cx', 'CallPattern')
    CallPattern.objects.update(name="")

class Migration(migrations.Migration):

    dependencies = [
        ('cdr3cx', '0012_add_name_to_callpattern'),
    ]

    operations = [
        migrations.RunPython(populate_callpattern_names, reverse_populate_callpattern_names),
    ]