# Generated by Django 5.0.7 on 2026-06-05 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acd', '0001_initial'),
        ('cdr3cx', '0014_callrecord_vendor_neutral'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecord',
            name='abandoned',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_records', to='acd.agent'),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='call_disposition',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='currency',
            field=models.CharField(blank=True, default='SAR', max_length=3),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='direction',
            field=models.CharField(blank=True, choices=[('inbound', 'Inbound'), ('outbound', 'Outbound'), ('internal', 'Internal'), ('unknown', 'Unknown')], db_index=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='hold_time',
            field=models.IntegerField(blank=True, help_text='Hold time in seconds', null=True),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='ingest_transport',
            field=models.CharField(blank=True, choices=[('socket', 'Legacy Socket'), ('db_pull', '3CX DB Pull'), ('csv', 'CSV Import'), ('api', 'REST API')], default='socket', max_length=16),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='queue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_records', to='acd.queue'),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='ring_time',
            field=models.IntegerField(blank=True, help_text='Ring time in seconds', null=True),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='wait_time',
            field=models.IntegerField(blank=True, help_text='Queue wait in seconds', null=True),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='wrap_time',
            field=models.IntegerField(blank=True, help_text='After-call work in seconds', null=True),
        ),
    ]
