# Generated by Django 5.0.7 on 2026-06-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdr3cx', '0015_callrecord_abandoned_callrecord_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquota',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
