# Generated by Django 5.1.4 on 2026-05-12 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0012_currency_and_company_locale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySecurityPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_timeout_minutes', models.PositiveIntegerField(default=480, help_text='Idle timeout for portal sessions (default 8h)')),
                ('enforce_ip_whitelist', models.BooleanField(default=False, help_text='If true and any whitelist entries exist, non-listed IPs are blocked.')),
                ('require_strong_password', models.BooleanField(default=True, help_text='Min length 12 + complexity rules')),
                ('password_history_size', models.PositiveSmallIntegerField(default=5, help_text='Block reuse of last N passwords')),
                ('password_max_age_days', models.PositiveSmallIntegerField(default=0, help_text='0 = no expiry; otherwise force reset after N days')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_policy', to='accounts.company')),
            ],
            options={
                'verbose_name_plural': 'Company security policies',
            },
        ),
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(blank=True, default='', help_text='Snapshot of email at action time', max_length=255)),
                ('method', models.CharField(db_index=True, max_length=8)),
                ('path', models.CharField(db_index=True, max_length=512)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('object_repr', models.CharField(blank=True, default='', help_text='Short label for the affected object', max_length=255)),
                ('extra', models.JSONField(blank=True, default=dict, help_text='Diff or context payload')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_log_entries', to='accounts.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', '-created_at'], name='security_au_company_c2969f_idx'), models.Index(fields=['user', '-created_at'], name='security_au_user_id_493ed9_idx')],
            },
        ),
        migrations.CreateModel(
            name='CompanyIpWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidr', models.CharField(help_text='IP or CIDR (e.g. 203.0.113.5 or 203.0.113.0/24)', max_length=43)),
                ('label', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_whitelist_entries', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company', 'cidr'],
                'unique_together': {('company', 'cidr')},
            },
        ),
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='security_pa_user_id_dd994e_idx')],
            },
        ),
    ]
