# Generated by Django 5.0.7 on 2025-05-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_smtpsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smtpsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
