# Generated by Django 5.0.7 on 2025-05-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('company_admin', 'Company Admin'), ('user', 'User (Readonly)')], default='user', max_length=20),
        ),
    ]
