# Generated by Django 5.0.7 on 2025-05-19 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='disable_external_call',
            field=models.BooleanField(default=False, help_text='If checked, external calls are disabled for this extension.'),
        ),
    ]
