# Generated by Django 5.0.7 on 2026-06-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_currency_and_company_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='pbx_source_ips',
            field=models.CharField(blank=True, default='', help_text="Comma-separated IP or CIDR (e.g. 5.42.225.171, 203.0.113.0/24) that may send CDRs to this company's listening port. Leave blank to allow any source (no restriction).", max_length=255, verbose_name='Allowed PBX source IP(s)'),
        ),
    ]
