# Generated by Django 5.0.7 on 2026-06-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_company_pbx_source_ips'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='pbx_api_password',
            field=models.CharField(blank=True, default='', help_text='3CX XAPI password.', max_length=128),
        ),
        migrations.AddField(
            model_name='company',
            name='pbx_api_url',
            field=models.CharField(blank=True, default='', help_text='e.g. https://smasco.3cx.ae:5001 — enables real queue ASA/SLA via the 3CX XAPI.', max_length=255, verbose_name='3CX API base URL'),
        ),
        migrations.AddField(
            model_name='company',
            name='pbx_api_user',
            field=models.CharField(blank=True, default='', help_text='3CX XAPI username (an admin / system-owner extension).', max_length=64),
        ),
    ]
