# Generated by Django 5.0.7 on 2026-06-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_company_pbx_api_password_company_pbx_api_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='extension',
            name='enabled',
            field=models.BooleanField(default=True, help_text="3CX 'Enabled' flag at last sync."),
        ),
        migrations.AddField(
            model_name='extension',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Still present in 3CX as of the last sync (soft-delete flag).'),
        ),
        migrations.AddField(
            model_name='extension',
            name='is_registered',
            field=models.BooleanField(default=False, help_text="3CX 'IsRegistered' at last sync (phone online)."),
        ),
        migrations.AddField(
            model_name='extension',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extension',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='extension',
            name='outbound_caller_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='extension',
            name='pbx_user_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='3CX Users.Id (for direct XAPI lookup/PATCH).', null=True),
        ),
        migrations.AddField(
            model_name='extension',
            name='source_pbx',
            field=models.CharField(default='3cx', max_length=20),
        ),
    ]
