# Generated by Django 5.0.7 on 2026-06-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_extension_display_name_extension_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, help_text='Company logo shown in the sidebar and on PDF reports.', null=True, upload_to='company_logos/'),
        ),
    ]
