# Generated by Django 5.0.7 on 2026-06-06 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_company_pbx_api_password_company_pbx_api_url_and_more'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('source', models.CharField(choices=[('fraud', 'Fraud incidents'), ('acd_sla', 'ACD SLA breaches'), ('quota', 'Quota exhaustion')], max_length=16)),
                ('min_severity', models.CharField(default='high', help_text='low/medium/high/critical (fraud) or amber/red (ACD)', max_length=10)),
                ('channels', models.CharField(default='email', help_text='Comma list: email, sms, whatsapp', max_length=80)),
                ('recipients', models.TextField(help_text='Emails / phone numbers, comma separated')),
                ('escalate_after_minutes', models.PositiveIntegerField(default=0, help_text='0 = no escalation')),
                ('escalate_recipients', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, help_text='Null = applies to all tenants', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='accounts.company')),
            ],
            options={
                'ordering': ['company', 'source', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=16)),
                ('severity', models.CharField(blank=True, default='', max_length=10)),
                ('summary', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, default='', help_text='Source object id (e.g. FraudIncident pk)', max_length=64)),
                ('channels_sent', models.CharField(blank=True, default='', max_length=80)),
                ('delivered', models.BooleanField(default=False)),
                ('escalated', models.BooleanField(default=False)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_events', to='accounts.company')),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='notifications.alertrule')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', '-created_at'], name='notificatio_company_b87851_idx'), models.Index(fields=['source', 'escalated'], name='notificatio_source_f7cecc_idx')],
            },
        ),
    ]
