# Generated by Django 6.0.6 on 2026-06-15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('digit', models.CharField(help_text='DTMF key the caller presses for this answer (e.g. 1, 0, *, #).', max_length=4)),
                ('label', models.CharField(help_text='What this answer means, e.g. "Very satisfied" or "Yes".', max_length=128)),
                ('score', models.FloatField(blank=True, help_text='Numeric value used for CSAT/NPS scoring. Leave blank if not scored.', null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='surveys.surveyquestion')),
            ],
            options={
                'ordering': ['question', 'order'],
                'unique_together': {('question', 'digit')},
            },
        ),
    ]
